CREATE TABLE ONLINE_CUSTOMER
(
    CID INT,
    Name VARCHAR(50),
    CITY VARCHAR(50)
);

INSERT INTO ONLINE_CUSTOMER VALUES
(101, 'RAHUL', 'RAJKOT'),
(103, 'PTIYA', 'SURAT'),
(106, 'DHARMIK', 'SURAT'),
(107, 'MEHUL', 'MORBI');

CREATE TABLE OFFLINE_CUSTOMER
(
    CID INT,
    Name VARCHAR(50),
    CITY VARCHAR(50)
);

INSERT INTO OFFLINE_CUSTOMER VALUES
(102, 'AMIT', 'AHMEDABAD'),
(104, 'HETVI', 'BARODA'),
(105, 'RIYA', 'RAJKOT'),
(106, 'DHARMIK', 'SURAT');

CREATE TABLE CUSTOMER
(
    CID INT,
    Name VARCHAR(50),
    CITY VARCHAR(50),
    MEMBERSHIP VARCHAR(20)
);

INSERT INTO CUSTOMER VALUES
(101, 'RAHUL', 'RAJKOT', 'GOLD'),
(102, 'AMIT', 'AHMEDABAD', 'SILVER'),
(103, 'PTIYA', 'SURAT', 'GOLD'),
(104, 'HETVI', 'BARODA', 'PLATINUM'),
(105, 'RIYA', 'RAJKOT', 'SILVER'),
(106, 'DHARMIK', 'SURAT', 'GOLD'),
(108, 'ISHITA', 'RAJOT', 'GOLD');